# -*- coding: utf-8 -*-
"""Py_Project_No1._HR-Analytics Synapse Solutions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cFkbkKEan5NNgVXHks_JNwM8tDDQMZSA

# **GIAI ĐOẠN I: Chuẩn bị & Tiền xử lý dữ liệu (Data Preparation & Cleaning)**
*Giai đoạn này đảm bảo nền móng dữ liệu vững chắc, không có rác hay sai lệch logic.*

**Công cụ chủ đạo:** Python (Pandas) hoặc SQL.

**Nhiệm vụ cụ thể:**
1.   **Đọc dữ liệu (Data Ingestion):** [Nguồn data, cách nạp].
2.   **Khắc phục lỗi định dạng (Formatting):** [Đổi tên file lỗi? Chuẩn hóa tên cột?]
3.   **Xử lý Null/Missing values (Handling Null/Missing/Error Values):** [Áp dụng phương pháp nào (mean, median, drop...)? Tại sao lại dùng cách đó?].
4.   **Scim các lỗi cơ bản theo Domain Knowledge:** [Xem xét các điểm dị thường như giá trị âm, hay vượt ngưỡng mức yêu cầu của cột].

*=> Kết quả của mục này: Có được Data Description của dữ liệu*

## **1.1 Đọc dữ liệu (Data Ingestion):**

### *1.1.1 Tổng quan về dữ liệu & Mục đích Phân tích*

**Dữ liệu:** Đây là dữ liệu nhân sự của công ty Synapse Solution, có tổng cộng 1000 nhân viên trong khoảng thời gian từ 1971 - 2023 (đây là dữ liệu giả lập).

**Mục đích:** Trả lời các câu hỏi trọng tâm sau:

* Tìm hiểu lý do tại sao nhân viên lại rời khỏi Công ty? Có tình trạng chảy máu chất xám không? => Đánh giá hiệu quả tuyển dụng !!!

* Phân tích các nguồn tuyển dụng?

* Tình hình Nhân sự tổng quát?
"""

# Import pandas để lấy dữ liệu
import pandas as pd
# Display (cấu trúc) dữ liệu nhận vào xuất hiện không giới hạn (loại bỏ ...)
pd.set_option('display.max_columns',None)

from google.colab import files
import io

# Import file của file của bạn vào đây
link='https://drive.google.com/file/d/1gFHi8kzNmeuwWtNG4ZndM_tHCVALig54/view' #Lấy link google drive của bạn vào đây
path = 'https://drive.google.com/uc?export=download&id=' + link.split('/')[-2]
uploaded = pd.read_excel(path)

import requests
import io

# The 'uploaded' variable from the previous cell is a pandas DataFrame.
# The code below expects 'uploaded' to be a dictionary from google.colab.files.upload()
# (i.e., {filename: bytes_content}).
# This is a fundamental mismatch. To make the cell functional, we need to retrieve the file bytes.

# Reconstructing `path` from `link` which is assumed to be available from the kernel state.
# If 'link' is not in scope, you might need to manually define it or ensure it's passed.
# For this notebook context, 'link' is 'https://drive.google.com/file/d/1gFHi8kzNmeuwWtNG4ZndM_tHCVALig54/view'
# and 'path' is 'https://drive.google.com/uc?export=download&id=1gFHi8kzNmeuwWtNG4ZndM_tHCVALig54'

# Assuming `path` variable (download URL) is available from the previous cell's execution.
# In a real scenario, you might pass `path` explicitly or redefine it.
# Here, we hardcode the file_id for robustness in this isolated cell fix.
file_id = '1gFHi8kzNmeuwWtNG4ZndM_tHCVALig54'
download_url = f'https://drive.google.com/uc?export=download&id={file_id}'

try:
    response = requests.get(download_url)
    response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
    file_bytes = response.content

    # Now, create a dictionary mimicking `files.upload()` output structure
    excel_file_name = "downloaded_from_drive.xlsx" # Assign a generic name
    uploaded_files_dict = {excel_file_name: file_bytes}

    # The original `if not uploaded:` needs to check the new dictionary
    if not uploaded_files_dict:
        print("Không có file Excel nào được tải lên. Vui lòng thử lại.")
    else:
        # Use the prepared dictionary `uploaded_files_dict`
        actual_excel_file_name = next(iter(uploaded_files_dict))
        print(f"\nĐã nhận file Excel: {actual_excel_file_name}")
        print(f"Kích thước file: {len(uploaded_files_dict[actual_excel_file_name])} bytes")
        try:
            # Use the bytes content from the dictionary to parse all sheets
            xls = pd.ExcelFile(io.BytesIO(uploaded_files_dict[actual_excel_file_name]))
            sheet_names = xls.sheet_names
            print(f"\nCác sheet có trong file '{actual_excel_file_name}': {sheet_names}")
            for sheet_name in sheet_names:
                print(f"\nĐang xử lý sheet: '{sheet_name}'...")
                try:
                    df_sheet = xls.parse(sheet_name)
                    csv_file_name = f"{sheet_name.replace(' ', '_')}.csv"
                    df_sheet.to_csv(csv_file_name, index=False, encoding='utf-8')
                    print(f"Đã lưu sheet '{sheet_name}' thành công thành file '{csv_file_name}'")
                except Exception as e_sheet:
                    print(f"Lỗi khi xử lý sheet '{sheet_name}': {e_sheet}")
            print("\nHoàn tất quá trình chuyển đổi tất cả các sheet thành file CSV!")
        except Exception as e_excel:
            print(f"Có lỗi xảy ra khi đọc hoặc xử lý file Excel '{actual_excel_file_name}': {e_excel}")
            print("Hãy đảm bảo file bạn tải lên là file Excel (.xlsx) hợp lệ.")

except requests.exceptions.RequestException as e:
    print(f"Lỗi khi tải file từ Google Drive: {e}")
    print("Hãy đảm bảo đường dẫn Google Drive hợp lệ và file có quyền truy cập công khai hoặc được xác thực.")

# Đặt tên cho dữ liệu nhận vào thông qua link bằng phương thức read_csv
df_Employ = pd.read_csv('/content/Employee.csv')
df_Hire = pd.read_csv('/content/Hiring.csv')
df_Perf = pd.read_csv('/content/Performance.csv')
df_Comp = pd.read_csv('/content/Compenstaion.csv')
df_Exit = pd.read_csv('/content/Exit_Interview.csv')

"""#### **Bảng số 1:** *df_Employ*"""

df_Employ

df_Employ.info()

df_Employ['Date Hired'] = pd.to_datetime(df_Employ['Date Hired'], format= '%Y-%m-%d',errors= 'coerce')

df_Employ

df_Employ.info()

"""**Data Dictionary của bảng Employee**

| **Tên cột - Column Name** | **Mô tả - Description** | **Kiểu dữ liệu - Data Type** | **Ghi chú/ Quy ước - Encoding / Notes** |
| :---------------- | :---------------------------------------------- | :------------ | :------------------------------------------------------------------------------------------------- |
| `Employee_ID` | Mã định danh nhân viên | `Integer` | Khóa chính (Primary Key). Tuyệt đối không được null hay trùng lặp. |
| `Name` | Họ và tên nhân viên | `String` | Có thể cần tách First Name / Last Name tùy yêu cầu sau này. |
| `email` | Email cá nhân/công ty | `String` | Cần kiểm tra định dạng email hợp lệ. |
| `gender` | Giới tính | `String (Category)` | Các giá trị dự kiến: Male, Female (Có thể có Khác/Other). |
| `Department` | Phòng ban làm việc | `String (Category)` | Cần chuẩn hóa tên (vd: "Human Resources" vs "HR"). |
| `Education level` | Trình độ học vấn | `String (Category)` | Vd: PhD, Master's Degree, Bachelor's Degree, v.v. |
| `Date Hired` | Ngày gia nhập công ty | `Date (YYYY-MM-DD)` | Dùng để tính Thâm niên (Tenure). Không thể lớn hơn ngày hiện tại. |
| `Still Employed` | Trạng thái còn làm việc | `Boolean` | `True` = Đang làm, `False` = Đã nghỉ việc. Khớp với bảng Exit_Interview. |
| `Work-Life Balance Score` | Điểm cân bằng công việc - cuộc sống | `Integer` | Thang điểm nội bộ (Dự kiến: 1 đến 5). 1 là tệ nhất, 5 là tốt nhất. |
| `Absenteeism Rate` | Mức độ vắng mặt | `String (Category)` | Mapping: Low, Moderate, High. Cần tìm hiểu định mức của HR (Low là < bao nhiêu %). |
"""

df_Employ.describe()

df_Employ.describe(include= 'O')

"""#### **Bảng số 2:** *df_Hire*"""

df_Hire

df_Hire.info()

"""**Data Dictionary của bảng Hiring**

| **Tên cột - Column Name** | **Mô tả - Description** | **Kiểu dữ liệu - Data Type** | **Ghi chú/ Quy ước - Encoding / Notes** |
| :---------------- | :---------------------------------------------- | :------------ | :------------------------------------------------------------------------------------------------- |
| `Employee_ID` | Mã định danh nhân viên | `Integer` | Khóa ngoại (Foreign Key). |
| `Source of Hire` | Nguồn tuyển dụng | `String (Category)` | Vd: Social media, Recruiter, Job board, Employee referral. |
| `Starting Salary` | Mức lương khởi điểm | `Float/Decimal` | Cần dùng SQL/Python đối chiếu xem có khớp 100% với cột cùng tên ở bảng Compensation không. |
"""

df_Hire.describe()

df_Hire.describe(include= 'O')

"""#### **Bảng số 3:** *df_Perf*"""

df_Perf

df_Perf.info()

"""**Data Dictionary của bảng Performance**

| **Tên cột - Column Name** | **Mô tả - Description** | **Kiểu dữ liệu - Data Type** | **Ghi chú/ Quy ước - Encoding / Notes** |
| :---------------- | :---------------------------------------------- | :------------ | :------------------------------------------------------------------------------------------------- |
| `Employee_ID` | Mã định danh nhân viên | `Integer` | Khóa ngoại (Foreign Key). |
| `Performance Review Score` | Điểm đánh giá hiệu suất | `String (Ordinal)` | Dữ liệu dạng thứ bậc: Exceptional > Outstanding > Superior > Excellent > Good > Satisfactory > Average > Needs Improvement > Below Expectations > Unsatisfactory. |
| `Training Courses Attended`| Khóa đào tạo đã tham gia | `String` | Có thể một người tham gia nhiều khóa (nếu dữ liệu dạng list, cần bóc tách - Explode trong Python). |
"""

df_Perf.describe()

df_Perf.describe(include= 'O')

"""#### **Bảng số 4:** *df_Comp*"""

df_Comp

df_Comp.info()

"""**Data Dictionary của bảng Compensation**

| **Tên cột - Column Name** | **Mô tả - Description** | **Kiểu dữ liệu - Data Type** | **Ghi chú/ Quy ước - Encoding / Notes** |
| :---------------- | :---------------------------------------------- | :------------ | :------------------------------------------------------------------------------------------------- |
| `Employee_ID` | Mã định danh nhân viên | `Integer` | Khóa ngoại (Foreign Key) liên kết với bảng Employee. |
| `Current Salary` | Mức lương hiện tại | `Float/Decimal` | Giá trị phải > 0. (Đơn vị: VND hoặc USD, cần xác nhận lại). |
| `Benefits` | Phúc lợi chính đang nhận | `String` | Vd: performance bonuses, gym membership. |
| `Source of Hire` | Nguồn tuyển dụng | `String (Category)` | **CẢNH BÁO TRÙNG LẶP**: Cột này cũng xuất hiện ở bảng Hiring. |
| `Starting Salary` | Mức lương khởi điểm | `Float/Decimal` | **CẢNH BÁO TRÙNG LẶP**: Cột này cũng có ở bảng Hiring. Phải `Current >= Starting` (nếu không bị giáng chức). |
| `Salary Growth (%)` | Tỷ lệ tăng trưởng lương | `Float` | Công thức: `((Current - Starting) / Starting) * 100`. Lưu ý: Đã phát hiện giá trị ÂM (vd: -54.36%), cần làm rõ đây là lỗi nhập liệu hay nhân viên bị cắt giảm lương. |
| `Promoted` | Đã từng được thăng chức chưa? | `String (Boolean)` | Ánh xạ: "Yes" (Có) / "No" (Không). |
"""

df_Comp.describe()

df_Comp.describe(include= 'O')

import numpy as np

def check_data_consistency(df_Hire, df_Comp):
    """
    Hàm kiểm tra tính đồng nhất 100% của các cột bị trùng lặp giữa 2 bảng.

    LÝ DO & PHÂN TÍCH THUẬT TOÁN:
    - Tại sao dùng pd.merge: Để đảm bảo so sánh đúng người (cùng Employee_ID),
      tránh trường hợp hai bảng bị sắp xếp lộn xộn thứ tự dòng.
    - Ưu điểm: Tuyệt đối chính xác, an toàn, hỗ trợ xuất ra các dòng bị lỗi.
    - Tối ưu hóa hiệu năng: Thay vì Merge toàn bộ bảng (tốn RAM), chúng ta
      chỉ 'select' đúng Khóa chính và các cột cần so sánh. Tốc độ thực thi
      O(N log N) nhanh gấp hàng trăm lần so với việc dùng iterrows() O(N^2).
    """
    print("--- BẮT ĐẦU KIỂM TRA ĐỒNG NHẤT DỮ LIỆU ---")

    # Bước 1: Merge 2 bảng (Chỉ lấy các cột cần thiết để tối ưu bộ nhớ)
    # Hậu tố _hiring và _comp sẽ được tự động thêm vào tên cột nếu trùng nhau
    df_merged = pd.merge(
        df_Hire[['Employee_ID', 'Source of Hire', 'Starting Salary']],
        df_Comp[['Employee_ID', 'Source of Hire', 'Starting Salary']],
        on='Employee_ID',
        how='inner',
        suffixes=('_hiring', '_comp')
    )

    # Bước 2: So sánh bằng Vectorization (Rất nhanh)
    # Toán tử == sẽ trả về một Series gồm True/False. Hàm .all() kiểm tra xem tất cả có phải True hay không.
    is_source_match = (df_merged['Source of Hire_hiring'] == df_merged['Source of Hire_comp']).all()
    is_salary_match = (df_merged['Starting Salary_hiring'] == df_merged['Starting Salary_comp']).all()

    # Bước 3: In kết quả
    print(f"1. Cột 'Source of Hire' khớp 100% không? -> {'CÓ' if is_source_match else 'KHÔNG'}")
    print(f"2. Cột 'Starting Salary' khớp 100% không? -> {'CÓ' if is_salary_match else 'KHÔNG'}")

    # Bước 4: Xử lý ngoại lệ (Trích xuất dữ liệu lỗi)
    if not (is_source_match and is_salary_match):
        print("\n[CẢNH BÁO] Phát hiện dữ liệu mâu thuẫn! Dưới đây là các dòng bị lệch:")

        # Tìm các dòng có Source hoặc Salary không khớp
        mismatch_condition = (
            (df_merged['Source of Hire_hiring'] != df_merged['Source of Hire_comp']) |
            (df_merged['Starting Salary_hiring'] != df_merged['Starting Salary_comp'])
        )

        df_errors = df_merged[mismatch_condition]
        print(df_errors.head()) # In ra 5 dòng lỗi đầu tiên để kiểm tra
    else:
        print("\n[KẾT LUẬN TỐI ƯU] Dữ liệu khớp 100%. ĐỀ XUẤT: Bạn CÓ THỂ LOẠI BỎ bảng 'Hiring.csv' khi xây dựng Model trong Power BI để tránh dư thừa.")


check_data_consistency(df_Hire, df_Comp)

"""#### **Bảng số 5:** *df_Exit*"""

df_Exit = pd.read_csv('/content/Exit_Interview.csv')

df_Exit

df_Exit.info()

df_Exit['Unnamed: 4'] = df_Exit['Unnamed: 4'].str.strip()

df_Exit['Last day of Employment'] = pd.to_datetime(df_Exit['Last day of Employment'],format= '%Y-%m-%d', errors= 'coerce')

df_Exit.info()

"""**Data Dictionary của bảng Exit_Interview**

| **Tên cột - Column Name** | **Mô tả - Description** | **Kiểu dữ liệu - Data Type** | **Ghi chú/ Quy ước - Encoding / Notes** |
| :---------------- | :---------------------------------------------- | :------------ | :------------------------------------------------------------------------------------------------- |
| `Employee_ID` | Mã định danh nhân viên | `Integer` | Khóa ngoại (Foreign Key). |
| `Reason for Leaving` | Lý do nghỉ việc (Chi tiết) | `String` | Lý do chi tiết do nhân viên cung cấp (Vd: Company downsizing, Career change). |
| `Last day of Employment` | Ngày làm việc cuối cùng | `Date (YYYY-MM-DD)` | Dùng để tính số ngày làm việc thực tế (Thâm niên = Last day - Date Hired). Phải sau `Date Hired`. |
| `Standardized Reason...` | Lý do nghỉ việc (Đã chuẩn hóa) | `String (Category)` | Phân loại từ HR (Vd: Involuntary Layoff, Voluntary Resignation, Personal Reasons). Rất hữu ích cho biểu đồ phân tích EDA. |
| `Unnamed: 4` | Cột rác / Phân loại tự nguyện | `String` | **RÁC DỮ LIỆU**: Tên cột bị lỗi (Unnamed). Chứa giá trị như "Voluntary". Cần làm sạch (Clean) hoặc Drop cột này bằng Python/SQL. |
"""

df_Exit.describe()

df_Exit.describe(include= 'O')

df_Exit[df_Exit['Unnamed: 4'] != 'Voluntary']

"""Dựa trên cột Unamed chỉ có 2 loại là `Voluntary`"""

df_Exit[df_Exit['Unnamed: 4'] != 'Voluntary']

# Xác định xem cột số 3 có bao nhiêu giá trị unique, phù hợp với tình nguyện bị đuổi hay không
df_Exit['Standardized Reason for Leaving'].unique()
# Dựa trên nhìn nhận cá nhân, ta thấy được,

import re
import unicodedata
# Tạo hàm để chuẩn hóa tên cột
def remove_vietnamese_accents(text):
    """Hàm phụ trợ: Xóa dấu tiếng Việt bằng unicodedata"""
    if not isinstance(text, str):
        return text
    # 1. normalize('NFKD'): Tách ký tự gốc và dấu (Ví dụ: 'á' -> 'a' và dấu sắc)
    # 2. encode('ASCII', 'ignore'): Ép về chuẩn mã ASCII, tự động vứt bỏ các dấu không thuộc ASCII
    # 3. decode('utf-8'): Chuyển ngược lại thành chuỗi String bình thường
    return unicodedata.normalize('NFKD', text).encode('ASCII', 'ignore').decode('utf-8')

def chuan_hoa_ten_cot(df):
    """Hàm chuẩn hóa toàn bộ tên cột trong DataFrame"""
    # 1. Chuyển thành chữ thường
    cols = df.columns.str.lower()

    # 2. (Tùy chọn nâng cao) Xóa bỏ các ký tự đặc biệt không phải chữ/số (như %, (), dấu phẩy...)
    cols = cols.str.replace(r'[^\w\s]', '', regex=True)

    # 3. Xóa khoảng trắng 2 đầu
    cols = cols.str.strip()

    # 4. Loại bỏ dấu tiếng Việt (Áp dụng hàm phụ trợ qua .map)
    cols = cols.map(remove_vietnamese_accents)

    # 5. Thay thế khoảng trắng ở giữa bằng dấu gạch dưới '_'
    cols = cols.str.replace(' ', '_', regex=False)

    # 6. Gán lại tên cột cho DataFrame
    df.columns = cols
    return df

chuan_hoa_ten_cot(df_Exit)

df_Exit[df_Exit['unnamed_4'] != 'Voluntary'].standardized_reason_for_leaving.unique()

"""Ta thấy rất rõ, đang có sự không phân định rõ ràng nhóm Voluntart trong 4 nhóm này, nên rõ ràng đây là dữ liệu bị thiếu, mập mờ, và chưa hoàn toàn rõ ràng => Giải pháp là loại bỏ hoàn toàn cột unnamed_4 này"""

df_Exit.drop(columns= 'unnamed_4',inplace= True)

df_Exit

df_Exit.info()

df_Exit.standardized_reason_for_leaving.unique()

df_Exit.reason_for_leaving.unique()

# Xác định xem các giá trị Null tại cột số 4 lý do là gì
df_Exit[df_Exit['standardized_reason_for_leaving'].isna()].reason_for_leaving.unique()

df_Exit[df_Exit['standardized_reason_for_leaving'].notna()].reason_for_leaving.unique()

"""Dựa trên code trên ta nhìn nhận được, những nhóm không xác định được lý do chuẩn để phân nhóm nghỉ gồm 6 nhóm sau:

*   Found a better opportunity: Tìm cơ hội tốt hơn
*   Relocation: Chuyển đổi đơn vị làm
*   Retirement: Nghỉ hưu
*   Lack of growth opportunities: Thiếu cơ hội phát triển
*   Personal reasons: Lý do cá nhân
*   Contract ended: Hết hạn HĐ lao động (cả 2 bên đều không gia hạn)

Để tối ưu theo cách làm công ty Synapse Solutions, ta sẽ vẫn chia luồng lý do nghỉ việc của nhân viên làm 2 cấp:

1. Cấp 1: `turnover_type` - bao gồm 2 loại là Voluntary và Involuntary.
2. Cấp 2: `root_cause_leaving` , chia cụ thể như sau:
*  Voluntary group: Career & Compensation ; Personal / Life Events ; Natural Attrition
*  Involuntary Group: Organizational Restructuring ; Contract Expiration

Để thực hiện việc này, ta sẽ tạo hàm để dùng phương thức `apply()` để áp dùng công thức
"""

def level_2_categories(categories):
  if categories in ['Company downsizing']:
    return 'Organizational Restructuring'
  if categories in ['Contract ended']:
    return 'Contract Expiration'
  if categories in ['Found a better opportunity','Lack of growth opportunities','Career change']:
    return 'Career & Compensation'
  if categories in ['Family commitments','Health reasons','Relocation','Personal reasons']:
    return 'Personal - Life Events'
  if categories in ['Retirement']:
    return 'Natural Attrition'
  else:
    return 'Unknown'

df_Exit['root_cause_leaving'] = df_Exit['reason_for_leaving'].apply(level_2_categories)
df_Exit

def level_1_categories(level_2_categories):
  if level_2_categories in ['Organizational Restructuring','Contract Expiration']:
    return 'Involuntary'
  if level_2_categories in ['Career & Compensation','Personal - Life Events','Natural Attrition']:
    return 'Voluntary'
  else:
    return 'Unknown'

df_Exit['turnover_type'] = df_Exit['root_cause_leaving'].apply(level_1_categories)
df_Exit

df_Exit[df_Exit['turnover_type'] == 'Involuntary'].standardized_reason_for_leaving.unique()

df_Exit[df_Exit['turnover_type'] == 'Voluntary'].standardized_reason_for_leaving.unique()

"""Sau khi thực hiện kiểm tra và hoàn thiện chuẩn hóa các lý do theo 2 nhóm như dự tính ban đầu của Công ty Synapse, ta sẽ thực hiện xóa nốt cột `standardized_reason_for_leaving`"""

df_Exit.drop(columns= 'standardized_reason_for_leaving', inplace= True)

df_Exit

df_Exit.info()

df_Exit.rename(columns={'employee_id' : 'Employee_ID'},inplace= True)

df_Exit

"""#### Sau khi thực hiện chuẩn hóa toàn bộ 5 bảng, ta sẽ thực hiện 2 bước sau:


1.   Xuất các bảng chuẩn về lại csv
2.   Thực hiện gộp các 5 bảng (Bỏ bảng df_Hire do trùng hoàn toàn với df_Comp)


"""

# Xuất ra file csv rồi tải xuống để nạp vào Power BI
df_Employ.to_csv('Employee_new.csv')
df_Hire.to_csv('Hiring_new.csv')
df_Perf.to_csv('Performance_new.csv')
df_Comp.to_csv('Compensation_new.csv')
df_Exit.to_csv('Exit_Interview_new.csv')

# Thực hiện gộp bảng
df_merge_employ_perf = pd.merge(
    df_Employ,df_Perf,
    on= 'Employee_ID',
    how= 'left'
)

df_merge_employ_perf.info()

df_merge_employ_perf_comp = pd.merge(
    df_merge_employ_perf,df_Comp,
    on= 'Employee_ID',
    how= 'left'
)

df_merge_employ_perf_comp.info()

df_HR_analyst = pd.merge(
    df_merge_employ_perf_comp,df_Exit,
    on= 'Employee_ID',
    how= 'left'
)

df_HR_analyst.info()

"""#### **Final Table:** *df_HR_analyst*

**Data Dictionary của bảng HR_Analytics**

| **Tên cột - Column Name** | **Mô tả - Description** | **Kiểu dữ liệu - Data Type** | **Ghi chú/ Quy ước - Encoding / Notes** |
| :------------------------ | :---------------------------------------------- | :--------------------------- | :------------------------------------------------------------------------------------------------- |
| `Employee_ID`             | Mã định danh duy nhất của nhân viên             | `Integer`                    | **[ĐỊNH DANH]** Khóa chính (Primary Key). Dùng để đếm số lượng Headcount.                          |
| `Name`                    | Họ và tên nhân viên                             | `String`                     | **[NHÂN KHẨU HỌC]** Dữ liệu định danh cá nhân.                                                     |
| `email`                   | Địa chỉ Email                                   | `String`                     | **[NHÂN KHẨU HỌC]** Thông tin liên hệ.                                                             |
| `gender`                  | Giới tính                                       | `String (Category)`          | **[NHÂN KHẨU HỌC]** Dùng phân tích Đa dạng & Hòa nhập (D&I).                                       |
| `Department`              | Phòng ban trực thuộc                            | `String (Category)`          | **[NHÂN KHẨU HỌC]** Dimension (Chiều phân tích) quan trọng nhất để cắt lớp KPIs.                   |
| `Education level`         | Trình độ học vấn cao nhất                       | `String (Category)`          | **[NHÂN KHẨU HỌC]** Quy ước: PhD, Master's, Bachelor's, v.v.                                       |
| `Date Hired`              | Ngày chính thức gia nhập công ty                | `Date (YYYY-MM-DD)`          | **[THỜI GIAN]** Dùng tính Thâm niên (Tenure) tính đến hiện tại hoặc ngày nghỉ việc.                |
| `Still Employed`          | Trạng thái hiện tại                             | `Boolean`                    | **[HIỆU SUẤT & GIỮ CHÂN]** `True` (Đang làm), `False` (Đã nghỉ). Dùng tính tỷ lệ Turnover.         |
| `Work-Life Balance Score` | Điểm đánh giá Cân bằng CS-CV                    | `Integer (1-5)`              | **[HIỆU SUẤT & GIỮ CHÂN]** Thang điểm: 1 = Tệ nhất, 5 = Tốt nhất.                                  |
| `Absenteeism Rate`        | Phân loại tỷ lệ vắng mặt                        | `String (Category)`          | **[HIỆU SUẤT & GIỮ CHÂN]** Quy ước: Low, Moderate, High. Cần chú ý nhóm High.                      |
| `Performance Review Score`| Xếp loại năng lực định kỳ                       | `String (Ordinal)`           | **[HIỆU SUẤT & GIỮ CHÂN]** Cấp độ từ Unsatisfactory đến Exceptional.                               |
| `Training Courses Attended`| Tên khóa đào tạo đã tham gia                    | `String`                     | **[ĐÀO TẠO]** Dùng để đếm số lượng và tính "Training Completion Rate".                             |
| `Current Salary`          | Mức lương hiện hành                             | `Float`                      | **[LƯƠNG THƯỞNG]** Dùng tính "HR Cost Per Employee" hoặc "Compa-Ratio".                            |
| `Starting Salary`         | Mức lương khởi điểm lúc vào làm                 | `Float`                      | **[LƯƠNG THƯỞNG]** Cơ sở tính tăng trưởng lương.                                                   |
| `Salary Growth (%)`       | Phần trăm tăng trưởng lương                     | `Float`                      | **[LƯƠNG THƯỞNG]** *Lưu ý: Nếu trong file gốc chưa xử lý các giá trị ÂM, cần phải filter/clean.* |
| `Benefits`                | Phúc lợi chính                                  | `String (Category)`          | **[LƯƠNG THƯỞNG]** Vd: 401k matching, gym membership, company car, v.v.                            |
| `Source of Hire`          | Kênh tuyển dụng đầu vào                         | `String (Category)`          | **[TUYỂN DỤNG]** Dùng đo lường "Sourcing Channel Effectiveness".                                   |
| `Promoted`                | Đã từng được thăng chức chưa?                   | `String (Yes/No)`            | **[ĐÀO TẠO & PHÁT TRIỂN]** Dùng tính "Internal Mobility Rate".                                     |
| `reason_for_leaving`      | Lý do nghỉ việc (Chi tiết)                      | `String`                     | **[NGHỈ VIỆC]** Chỉ có dữ liệu khi `Still Employed` = False. Còn lại là Null.                      |
| `last_day_of_employment`  | Ngày làm việc cuối cùng                         | `Date (YYYY-MM-DD)`          | **[NGHỈ VIỆC]** Khuyết thiếu (Null) nếu đang làm việc. Dùng tính Thâm niên thực tế.                |
| `root_cause_leaving`      | Nhóm nguyên nhân cốt lõi (Chuẩn hóa)            | `String (Category)`          | **[FEATURE MỚI]** (Vd: Personal, Career). Dùng để vẽ biểu đồ phân tích nguyên nhân gốc rễ.         |
| `turnover_type`           | Loại hình nghỉ việc                             | `String (Category)`          | **[FEATURE MỚI]** Trọng tâm để tính KPIs: (Voluntary - Tự nguyện / Involuntary - Bắt buộc).        |
"""

# Bắt đầu kiểm tra dữ liệu
df_HR_analyst.describe()

df_HR_analyst.describe(include= 'O')

"""Dựa trên bảng thống kê của dữ liệu, ta đúc kết các kết luận sơ bộ sau:

1. **Thông tin về nhân khẩu học** - `Employee_ID`, `gender`, `email`, `Education level`: Dữ liệu cho thấy Công ty Synapse Solutions có tổng cộng **1000 nhân viên**, mỗi nhân viên đều **có 1 email riêng biệt**, trong đó chiếm đa số là **nhân viên Nam** với **525 nhân viên** (còn lại là nữ). Trình độ chuyên môn của Công ty rất đa dạng, với tổng cộng 6 bậc học vấn, trong đó chiếm đa số là bậc **PhD (tiến sĩ)** với **179 nhân sự**, cho thấy Công ty sở hữu nguồn nhân lực có **trình độ cao**.
2. **Thông tin về tuyển dụng** - `Date Hired`, `Source of Hire`: Công ty có nguồn nhân lực làm việc từ năm 1971 cho đến năm 2023 (dữ liệu được lấy từ năm 2024), trung bình 50% nhân viên của công ty được tuyển dụng trong khoảng thập niên 2000s (50% dữ liệu là 2003), cho thấy nhân viên có mức độ gắn bó với doanh nghiệp ổn định. Ngoài ra, Công ty có đa dạng các nguồn tuyển dụng với **5 kênh** tuyển dụng, trong đó đa phần là nguồn **Recruiter** với 219 nhân sự được tuyển dụng từ kênh này.
3. **Thông tin về chế độ lương** - `Starting Salary`, `Current Salary`, `Salary Growth`, `Promoted`:


*   `Starting Salary`: mức thấp nhất là **50.000** và cao nhất là **95.000**, cho thấy nhân viên có mức thu nhập tương đối đồng đều, và phù hợp vì lương khởi đầu có thể dao động dựa trên kinh nghiệm, yêu cầu của vị trí công việc đặc thù (như vị trí lãnh đạo). Biên độ chênh lệch `std` dao động trong khoảng xấp xỉ **14.000**, không chênh lệch quá lớn, ở mức chấp nhận được. Điều này cho thấy lương khởi điểm giữa các vị trí có sự phân bổ hợp lý, có cơ sở.
*   `Current Salary`: mức thấp nhất là **40.000** và cao nhất là **150.000**, có sự khác biệt rõ rệt khi lương thấp nhất có sự giảm nhẹ, và lương cao nhất là có sự tăng đột biến, điều này cho thấy Công ty có các chế tài giảm lương nếu không đáp ứng yêu cầu của Công ty (thông thường, đây là điểm không tốt, sẽ có thể gặp trường hợp nhân viên kiện cáo nếu giảm lương thiếu cơ sở, nhất là so với mức khởi điểm - thông thường tối ưu là không nhận nhân viên nếu nhân viên không đạt yêu cầu, hoặc không tăng lương hoặc không gia hạn hợp đồng). Đối với mức cao nhất cho thấy Công ty có những nhân tố "đặc biệt", rất có thể đây là vai trò lãnh đạo, khi biên độ `std` chỉ có **31.000** nhưng độ chênh lệch giữa mức cao nhất của lương khởi điểm và lương hiện tại là quá cao.
*   `Salary Growth` , `Promoted`: mức thấp nhất là ~ **-58%**, giá trị âm cực lớn vì thông thường không thể mức độ tăng trưởng âm là quá lớn như vậy (rất có thể đây là giáng cấp, nhưng là giáng nhiều cấp, cần phải kiểm tra các giá trị âm có biên độ trên 10% những trường hợp như thế nào), mức cao nhất là ~ **200%**, một mức rất đáng kể. Rất có khả năng đây là mức tăng trưởng kể từ Salary cho tới Current, chứ không phải mức độ tăng trưởng trung bình. 50% nhân viên có mức độ tăng trưởng lương là **28%**, cho thấy đa phần nhân viên được tăng lương, hoàn toàn khớp với kết quả **511 nhân viên** được thăng tiến trong công việc. Mức độ chênh lệch `std` tới **53%** một mức chênh lệch vô cùng cao, càng củng cố thêm dữ liệu rằng công ty tính mức độ tăng trưởng bằng cách lấy Current / Starting. => Công ty cần làm mức độ tăng trưởng trung bình năm và trung bình xuyên suốt quãng đời công tác để đánh giá mức độ hiệu quả của nhân sự.

4. **Thông tin về các phúc lợi, chất lượng cuộc sống và hiệu suất làm việc của nhân viên** - `Work-Life Balance Score`, `Absenteeism Rate`, `Performance Review Score`, `Training Courses Attended`, `Benefits`:

*   `Work-Life Balance Score`, `Benefits`, `Training Courses Attended`: Điểm đánh giá chất lượng cuộc sống nhân viên ở mức trung bình **3 điểm**, cho thấy nhân viên có cuộc sống cân bằng, không bị áp lực công việc, ngoài ra, Công ty có đa dạng các Benefits, với tổng cộng **10 nhóm**, trong đó đa phần là **company cars** với 120 nhân viên được hưởng lợi, ngoài ra Công ty cũng thường xuyên đào tạo nội bộ, với đa dạng tổng cộng **10 khóa** đào tạo, và phần đông nhân viên chọn **Advanced Excel Techniques** với **112 nhân viên** tham dự.
*   `Absenteeism Rate`, `Performance Review Score`: Đa phần nhân viên đều ổn định, đi làm đúng giờ, tỷ lệ nhân viên vắng mặt tại nơi công sở là **Moderate**, với **355 nhân viên**, ngoài ra, ta thấy rất rõ `Performance Review Score`có độ phủ quá rộng, không thể đánh giá đủ tường tận xem đa phần nhân viên có làm việc hiệu quả không, cần gộp nhóm.

5. **Thông tin về tỷ lệ nghỉ việc**: Có tổng cộng 338 nhân viên nghỉ, với đa phần là tình nguyện nghỉ việc **Voluntary** với **277 nhân viên** (chiếm đến 82%). Có đến 10 lý do nghỉ việc, đa phần là các lý do thuộc nhóm **Personal - Life Events** với **135 nhân viên** (chiếm 40%).
"""

df_HR_analyst['Performance Review Score'].unique()

"""Dựa trên kết quả trên, ta có thể gom thành 3 nhóm chính về là High, Meet Expectation và Low. Ta sử dụng mapping để thực hiện gộp nhóm"""

# Tạo dictionary lưu trữ map
performance_mapping = {
    'Exceptional': 'High', 'Outstanding': 'High', 'Superior': 'High', 'Excellent': 'High',
    'Good': 'Meet Expectation', 'Satisfactory': 'Meet Expectation', 'Average': 'Meet Expectation',
    'Needs Improvement': 'Low', 'Below Expectations': 'Low', 'Unsatisfactory': 'Low'
}

# Tạo cột mới
df_HR_analyst['Performance_group'] = df_HR_analyst['Performance Review Score'].map(performance_mapping)
df_HR_analyst['Performance_group'].describe(include= 'O')

df_HR_analyst

def turnover_flag_convert(values):
    """
    Function to create the columns 'Turnover_flag', base in the results of boolean-value 'Still Employed' column
    Ideas:
        - If 'Still Employed' == True then value = 0
        - If 'Still Employed' == False then value = 1
        - If 'Still Employed' does not have the two boolean results, the function return NaN (null)
    Reason:
        - Help calculating Turnover Rate (%)
    """
    if values == True:
        return int(0)
    elif values == False:
        return int(1)
    return None

df_HR_analyst['Turnover_flag'] = df_HR_analyst['Still Employed'].apply(turnover_flag_convert)

df_HR_analyst['Turnover_flag']

# Create HR - Comparative Ratio to measure internal pay equity
# Identify ideas:
# Step 1: Calculate Avarage Salary following by Department:
# To do this, we must group by department, aggregations function is median
# However, if we groupby, basically, it would return dictionary, which cannot broadcasting value into each records (employee)
# Solution: we use method transform() from Pandas as window function (AVG(['Current Salary']) OVER (Partition by Departmet) AS Dept_Median_Salary) to calculate the results into each records
df_HR_analyst['Dept_Median_Salary'] = df_HR_analyst.groupby('Department')['Current Salary'].transform('median')

# Step 2: Calculate Compa-Ratio
df_HR_analyst['Compa_Ratio'] = df_HR_analyst['Current Salary'] / df_HR_analyst['Dept_Median_Salary']

df_HR_analyst

# Cuối cùng, xuất bảng để đưa vào Power BI
df_HR_analyst.to_csv('Updated_HR_Analytics.csv')

"""# **Giai đoạn 2: Phân tích Khám phá & Kỹ thuật Đặc trưng (EDA & Feature Engineering)**

*Giai đoạn đào sâu vào dữ liệu để tạo ra các biến mới phục vụ tính toán KPIs.*

## 2.1 Tổng quan Nguồn nhân lực & Chi phí Tuyển dụng (Demographic & Hiring)

**Mục tiêu chung:** Phác họa bức tranh toàn cảnh về "đầu vào" (Inbound) của Synapse Solution và đánh giá chất lượng các kênh tuyển dụng.

**Mục tiêu cụ thể:** Xác định cấu trúc nhân khẩu học hiện tại; Tìm ra kênh tuyển dụng mang lại giá trị cao nhất (giữ chân lâu) và kênh gây lãng phí nhất.

**Câu hỏi kinh doanh (Business Questions):**

*  **Câu hỏi Tổng quát:** Cấu trúc độ tuổi, giới tính và học vấn phân bổ như thế nào ở từng phòng ban?

*  **Câu hỏi Nguyên nhân (Lõi):** Kênh "Recruiter" (Headhunter) đem lại nhiều người nhất, nhưng mức lương khởi điểm có bị "đội" lên quá cao không? Và những người từ kênh này có tỷ lệ nghỉ việc cao hay thấp?

**Insight EDA cơ bản (Python):**

*  **Phân tích Đơn biến:** Dùng `sns.countplot()` vẽ phân bổ `Education level` theo `Department` để kiểm chứng giả thuyết "PhD làm sai phòng".

*  **Phân tích Đa biến:** Dùng `sns.boxplot()` so sánh `Starting Salary` giữa các `Source of Hire`. Xem mức độ chênh lệch lương đầu vào.

**Ý tưởng Dashboard Power BI (Power BI Blueprint):**

*  **Luồng thiết kế:** Trái (Tổng quan Nhân sự) -> Phải (Hiệu quả Tuyển dụng).

*  **Card KPIs (Trên cùng)**: Total Headcount, Total Hires, Avg Starting Salary.

*  **Biểu đồ (Chart Selection):**

    *  Donut Chart: Thể hiện Tỷ trọng Giới tính và Học vấn (Cái nhìn tổng quát).

    *  Decomposition Tree (Cây phân rã): Đi từ `Source of Hire` -> `Department` -> `Turnover_Flag`. (Lý do: Giúp người dùng tương tác để tìm ra cội nguồn của việc tuyển sai người).
"""

# ==============================================================================
# INSIGHT 1: TỔNG QUAN NGUỒN NHÂN LỰC & HIỆU QUẢ TUYỂN DỤNG
# ==============================================================================
import matplotlib.pyplot as plt
import seaborn as sns

print("--- VẼ BIỂU ĐỒ INSIGHT 1: DEMOGRAPHIC & HIRING ---")
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# 1. BIỂU ĐỒ TRÁI: Phân bổ Học vấn (Education) theo Phòng ban (Department)
# Lý do chọn biểu đồ: Countplot giúp nhìn rõ khối lượng (volume). Hue giúp tách lớp học vấn.
# Mục tiêu HR: Tìm xem nhóm PhD (Tiến sĩ) đang tập trung ở đâu. Có rủi ro Overqualification không?
sns.countplot(data=df_HR_analyst, y='Department', hue='Education level', palette='Set2', ax=axes[0])
axes[0].set_title('Phân bổ Học vấn theo Phòng ban', fontweight='bold')
axes[0].set_xlabel('Số lượng nhân sự (Người)')
axes[0].set_ylabel('Phòng ban')

# 2. BIỂU ĐỒ PHẢI: Lương khởi điểm (Starting Salary) theo Kênh Tuyển dụng
# Lý do chọn biểu đồ: Boxplot là "vua" trong việc tìm Outliers và phân tán lương.
# Mục tiêu HR: Kênh "Recruiter" đắt đỏ có thực sự mang lại người có mức lương khởi điểm (định giá thị trường) cao hơn không?
sns.boxplot(data=df_HR_analyst, x='Starting Salary', y='Source of Hire', palette='pastel', ax=axes[1])
axes[1].set_title('Phân bổ Lương khởi điểm theo Nguồn Tuyển dụng', fontweight='bold')
axes[1].set_xlabel('Lương khởi điểm ($)')
axes[1].set_ylabel('Nguồn tuyển dụng')

plt.tight_layout()
plt.show()

"""## 2.2 Đánh giá Hiệu suất & Năng suất (Performance Management)

**Mục tiêu chung:** Đánh giá tính minh bạch và hiệu quả của hệ thống đánh giá năng lực tại Synapse Solution.

**Mục tiêu cụ thể:** Kiểm tra xem quỹ điểm Performance có bị phân bổ sai lệch không; Xác định mối liên hệ giữa việc học tập (Training) và sự thăng tiến (Promotion).

**Câu hỏi kinh doanh (Business Questions):**

*  **Câu hỏi Tổng quát:** Có bao nhiêu % nhân sự đạt loại Giỏi/Xuất sắc? Có sự chênh lệch điểm số giữa các phòng ban không?
*  **Câu hỏi Nguyên nhân (Lõi):** Nhân viên có Thâm niên (Tenure) càng lâu thì làm việc càng hiệu quả? Tham gia nhiều khóa đào tạo (`Training Courses Attended`) có làm tăng tỷ lệ được thăng chức (`Promoted`) không?

**Insight EDA cơ bản (Python):**

*  **Data Transformation:** Nhóm (Binning) 10 mức `Performance Review Score` thành 3 mức: Low, Meet, High (Đã thực hiện).

*  **Phân tích Đa biến:** Dùng `sns.heatmap(crosstab)` để xem bảng chéo tương quan giữa số lượng khóa đào tạo và trạng thái `Promoted` (Có/Không).

**Ý tưởng Dashboard Power BI (Power BI Blueprint):**

*  **Luồng thiết kế:** Trái (Phân bổ Điểm số) -> Phải (Kết quả Thăng tiến).

*  **Card KPIs (Trên cùng)**: Avg Performance Score, Internal Mobility Rate (%).

*  **Biểu đồ (Chart Selection):**

    *  Ribbon Chart: So sánh thứ hạng xếp loại Hiệu suất giữa các Phòng ban. (Lý do: Dễ dàng thấy phòng nào đang "chấm điểm dễ dãi" nhất).

    *  100% Stacked Bar Chart: Phân bổ `Promoted` (Yes/No) chia theo Nhóm Hiệu suất (Low/Meet/High). (Lý do: Chứng minh logic Nguyên nhân - Kết quả: "Có phải cứ làm tốt là được thăng chức?").
"""

# ==============================================================================
# INSIGHT 2: ĐÁNH GIÁ HIỆU SUẤT & SỰ THĂNG TIẾN
# ==============================================================================
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("--- VẼ BIỂU ĐỒ INSIGHT 2: PERFORMANCE & MOBILITY ---")

# BƯỚC CHUẨN BỊ (DATA BINNING): Gom 10 mức Performance thành 3 mức cốt lõi
# Tối ưu hóa: Dùng dictionary mapping siêu tốc
perf_map = {
    'Exceptional': 'High', 'Outstanding': 'High', 'Superior': 'High', 'Excellent': 'High',
    'Good': 'Meet', 'Satisfactory': 'Meet', 'Average': 'Meet',
    'Needs Improvement': 'Low', 'Below Expectations': 'Low', 'Unsatisfactory': 'Low'
}
# Tạo cột mới, map những giá trị không có trong dict thành 'Unknown' để tránh lỗi Null
df_HR_analyst['Performance_Group'] = df_HR_analyst['Performance Review Score'].map(perf_map).fillna('Unknown')

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# 1. BIỂU ĐỒ TRÁI: Phân bổ Nhóm Hiệu suất theo Phòng ban (Leniency Bias)
# Lý do chọn: 100% Stacked Bar (Dùng Crosstab) để xem TỶ TRỌNG.
# Mục tiêu HR: Tìm xem phòng nào "chấm điểm dễ", phòng nào "chấm điểm gắt".
perf_crosstab = pd.crosstab(df_HR_analyst['Department'], df_HR_analyst['Performance_Group'], normalize='index') * 100
perf_crosstab[['Low', 'Meet', 'High']].plot(kind='barh', stacked=True, color=['#e74c3c', '#f1c40f', '#2ecc71'], ax=axes[0])
axes[0].set_title('Tỷ trọng Xếp loại Hiệu suất theo Phòng ban (100% Stacked)', fontweight='bold')
axes[0].set_xlabel('Tỷ lệ phần trăm (%)')
axes[0].set_ylabel('Phòng ban')
axes[0].legend(title='Nhóm Hiệu suất', bbox_to_anchor=(1, 1))

# 2. BIỂU ĐỒ PHẢI: Mối liên hệ giữa Điểm Hiệu suất và Việc Thăng chức (Promoted)
# Lý do chọn biểu đồ: Countplot phân màu (hue) thể hiện rõ độ lệch.
# Mục tiêu HR: Kiểm chứng logic "Trả thưởng công bằng" - Có phải cứ High Performance là được thăng chức?
sns.countplot(data=df_HR_analyst, x='Performance_Group', hue='Promoted', order=['Low', 'Meet', 'High'], palette='mako', ax=axes[1])
axes[1].set_title('Tương quan giữa Nhóm Hiệu suất và Thăng chức', fontweight='bold')
axes[1].set_xlabel('Nhóm Hiệu suất')
axes[1].set_ylabel('Số lượng (Người)')

plt.tight_layout()
plt.show()

"""## 2.3 Phân tích Cấu trúc Lương & Sự công bằng (Compensation & Benefits)

**Mục tiêu chung:** Minh bạch hóa quỹ lương và kiểm toán sự công bằng trong việc chi trả thu nhập cho nhân viên.

**Mục tiêu cụ thể:** Phát hiện các điểm bất thường (Outliers) trong lương hiện tại (`Current Salary`) và đánh giá chính sách "Trả lương theo năng lực" (Pay-for-Performance).

**Câu hỏi kinh doanh (Business Questions):**

*  **Câu hỏi Tổng quát:** Phòng ban nào đang chiếm dụng quỹ lương lớn nhất? Phúc lợi (Benefits) đắt đỏ như "Company Car" đang rơi vào tay ai?

*  **Câu hỏi Nguyên nhân (Lõi):** Có tồn tại sự bất công (Làm dở nhưng lương cao, Làm xuất sắc nhưng lương thấp) không? Tỷ lệ tăng trưởng lương (`Salary Growth`) có đồng biến với điểm `Performance` không?

**Insight EDA cơ bản (Python):**

*  **Feature Engineering**: Tính toán cột `Compa-Ratio` = `Current Salary` / `Median(Current Salary theo Dept)`.

*  **Phân tích Đa biến:** Vẽ `sns.scatterplot()` với trục X là Hiệu suất, trục Y là Lương hiện tại, để lộ ra những kẻ "Ngồi mát ăn bát vàng" (Góc trái trên của biểu đồ).

**Ý tưởng Dashboard Power BI (Power BI Blueprint):**

*  **Luồng thiết kế:** Trái (Tổng quan Quỹ lương) -> Phải (Sự công bằng Lương vs Hiệu suất).

*  **Card KPIs (Trên cùng)**: Total Payroll (Tổng quỹ lương), Avg Current Salary, Avg Salary Growth.

*  **Biểu đồ (Chart Selection):**

    *  Waterfall Chart: Phân tích sự tăng giảm của Quỹ lương từ Mức khởi điểm (`Starting`) lên Mức hiện tại (`Current`) theo từng Phòng ban.

    *  Scatter Plot (Biểu đồ phân tán): So sánh Điểm Performance (Trục X) và Compa-Ratio (Trục Y). (Lý do: Phương pháp kinh điển của HR để tìm ra nhóm nhân tài đang bị trả lương rẻ mạt).
"""

# ==============================================================================
# INSIGHT 3: CẤU TRÚC LƯƠNG & SỰ CÔNG BẰNG NỘI BỘ (COMPA-RATIO)
# ==============================================================================
import matplotlib.pyplot as plt
import seaborn as sns

print("--- VẼ BIỂU ĐỒ INSIGHT 3: COMPENSATION & COMPA-RATIO ---")

# FEATURE ENGINEERING TỐI ƯU HÓA: Tính Compa-Ratio bằng .transform()
# Ưu điểm: Nhanh hơn 10x so với viết vòng lặp for hoặc merge dataframes.

fig, axes = plt.subplots(1, 2, figsize=(18, 6))

# 1. BIỂU ĐỒ TRÁI: Phân tán Lương Hiện tại theo Phòng Ban
# Lý do chọn biểu đồ: Violinplot kết hợp ưu điểm của Boxplot (thấy trung vị) và Histogram (thấy hình dáng phân phối).
sns.violinplot(data=df_HR_analyst, x='Current Salary', y='Department', palette='coolwarm', inner='quartile', ax=axes[0])
axes[0].set_title('Phân phối Cấu trúc Lương theo Phòng ban', fontweight='bold')
axes[0].set_xlabel('Lương hiện tại ($)')

# 2. BIỂU ĐỒ PHẢI: Scatter Plot - Ma trận "Nhân tài bị bỏ quên"
# Lý do chọn biểu đồ: Tương quan 2 biến số (Trục X = Tăng trưởng, Trục Y = Compa-Ratio).
# Mục tiêu HR: Tìm góc dưới cùng bên phải (Lương đang thấp hơn mức trung bình < 1, nhưng Tăng trưởng cao / Hiệu suất High).
sns.scatterplot(
    data=df_HR_analyst[df_HR_analyst['Performance_Group'] == 'High'], # Chỉ soi nhóm Nhân viên Xuất sắc
    x='Salary Growth (%)',
    y='Compa_Ratio',
    hue='Department',
    alpha=0.7, s=80, ax=axes[1]
)
# Vẽ đường tham chiếu chuẩn (Compa-ratio = 1.0 là lương bằng đúng chuẩn thị trường)
axes[1].axhline(1.0, color='red', linestyle='--', label='Ngưỡng lương Trung bình (1.0)')
axes[1].set_title('Nhóm High-Performer: Tương quan Tăng trưởng Lương & Compa-Ratio', fontweight='bold')
axes[1].set_xlabel('Tăng trưởng Lương (%)')
axes[1].set_ylabel('Chỉ số Compa-Ratio')
axes[1].legend(bbox_to_anchor=(1.05, 1), loc='upper left')

plt.tight_layout()
plt.show()

"""## 2.4 Cân bằng Cuộc sống & Sự gắn kết (Work-Life Balance & Absenteeism)

**Mục tiêu chung:** Đo lường "Sức khỏe tinh thần" của tổ chức và phát hiện những khu vực có nguy cơ kiệt sức (Burnout).

**Mục tiêu cụ thể:** Tìm ra mối liên hệ giữa việc mất cân bằng cuộc sống (`Work-Life Balance Score`) với mức độ chểnh mảng công việc (`Absenteeism Rate`).

**Câu hỏi kinh doanh (Business Questions):**

*  **Câu hỏi Tổng quát:** Cấu trúc độ tuổi, giới tính và học vấn phân bổ như thế nào ở từng phòng ban?

*  **Câu hỏi Nguyên nhân (Lõi):** Kênh "Recruiter" (Headhunter) đem lại nhiều người nhất, nhưng mức lương khởi điểm có bị "đội" lên quá cao không? Và những người từ kênh này có tỷ lệ nghỉ việc cao hay thấp?

**Insight EDA cơ bản (Python):**

*  **Phân tích Tương quan:** Dùng `sns.heatmap()` để tạo ma trận tương quan (Correlation Matrix) giữa các biến dạng số: `WLB Score`, `Tenure`, và `Salary`.

*  **Phân tích Phân phối:** Dùng `sns.violinplot()` để xem độ phân tán của điểm WLB theo từng nhóm `Absenteeism Rate` (Low, Moderate, High).

**Ý tưởng Dashboard Power BI (Power BI Blueprint):**

*  **Luồng thiết kế:** Đi thẳng vào phân tích Nguyên nhân (WLB) -> Kết quả (Vắng mặt).

*  **Card KPIs (Trên cùng)**: Avg WLB Score, % High Absenteeism.

*  **Biểu đồ (Chart Selection):**

    *  Matrix (Bảng ma trận): Hàng là `Department`, Cột là `Absenteeism Rate`, Value là số lượng nhân sự. Áp dụng Conditional Formatting màu đỏ cho cột "High".

    *  Gauge Chart (Biểu đồ đồng hồ): Đo lường điểm WLB trung bình so với mục tiêu (Target) của HR là 4.0.
"""

# ==============================================================================
# INSIGHT 4: CÂN BẰNG CUỘC SỐNG & TỶ LỆ VẮNG MẶT
# ==============================================================================
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("--- VẼ BIỂU ĐỒ INSIGHT 4: WORK-LIFE BALANCE & ABSENTEEISM ---")
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# 1. BIỂU ĐỒ TRÁI: Heatmap mức độ Vắng mặt (Absenteeism) theo Phòng ban
# Thuật toán: Tạo bảng tần suất Crosstab
absent_crosstab = pd.crosstab(df_HR_analyst['Department'], df_HR_analyst['Absenteeism Rate'])
# Xếp lại thứ tự cột cho logic
if set(['Low', 'Moderate', 'High']).issubset(absent_crosstab.columns):
    absent_crosstab = absent_crosstab[['Low', 'Moderate', 'High']]

# Lý do chọn biểu đồ: Heatmap hiển thị màu đậm nhạt, đập vào mắt ngay phòng nào có khối màu "High" đỏ chót.
sns.heatmap(absent_crosstab, annot=True, fmt='d', cmap='Reds', ax=axes[0])
axes[0].set_title('Bản đồ Nhiệt: Mức độ Vắng mặt theo Phòng ban', fontweight='bold')
axes[0].set_xlabel('Tỷ lệ Vắng mặt')
axes[0].set_ylabel('Phòng ban')

# 2. BIỂU ĐỒ PHẢI: Boxplot Điểm Cân bằng (WLB) và Tỷ lệ Vắng mặt
# Mục tiêu HR: Chứng minh nhân quả - Có phải Vắng mặt nhiều là do WLB thấp?
sns.boxplot(data=df_HR_analyst, x='Work-Life Balance Score', y='Absenteeism Rate',
            order=['Low', 'Moderate', 'High'], palette='Set3', ax=axes[1])
axes[1].set_title('Tương quan: Điểm Cân bằng Cuộc sống & Mức độ Vắng mặt', fontweight='bold')
axes[1].set_xlabel('Điểm WLB (1-5)')
axes[1].set_ylabel('Mức độ Vắng mặt')

plt.tight_layout()
plt.show()

"""## 2.5 Đào sâu Tỷ lệ Nghỉ việc & Chảy máu chất xám (Turnover Root Cause Analysis)

**Mục tiêu chung:** Giải quyết bài toán đau đầu nhất của HR: Đóng vai trò làm "Trùm cuối" kết hợp 4 Insight trên để trả lời câu hỏi "Tại sao 33.8% nhân sự rời đi?".

**Mục tiêu cụ thể:** Bóc trần sự thật đằng sau hiện tượng "Polite Quitting" (Viện cớ lý do cá nhân) và xác định xem công ty có đang bị chảy máu nhân tài (Top Performers) không.

**Câu hỏi kinh doanh (Business Questions):**

*  **Câu hỏi Tổng quát:** Loại hình nghỉ việc (Tự nguyện vs Bắt buộc) phân bổ thế nào ở từng phòng ban?

*  **Câu hỏi Nguyên nhân (Lõi):**

    * Bao nhiêu phần trăm người nghỉ việc Tự nguyện là "High Performer" (Chảy máu chất xám)?

    * Những người báo cáo nghỉ vì "Lý do cá nhân" thực chất có mức Lương (hoặc WLB) thấp hơn những người ở lại không?

**Insight EDA cơ bản (Python):**

*  **Lọc Dữ liệu (Boolean Indexing):** Tạo một Dataframe riêng `df_voluntary` chỉ chứa những người nghỉ tự nguyện.

*  **Phân tích Sâu:** Vẽ `sns.boxplot()` kết hợp tham số hue để so sánh Mức lương trung bình của nhóm `root_cause_leaving` = Personal với nhóm `Still Employed` = True. Nếu lương họ thấp bẹt, ta kết luận được ngay sự thật.

**Ý tưởng Dashboard Power BI (Power BI Blueprint):**

*  **Luồng thiết kế:** Tổng quan Tỷ lệ Nghỉ việc -> Đi sâu vào nhóm "Tự nguyện" -> Phân rã nguyên nhân gốc rễ.

*  **Card KPIs (Trên cùng)**: Overall Turnover Rate (%), Voluntary Turnover Rate (%), Regrettable Turnover Rate (%).

*  **Biểu đồ (Chart Selection):**

    *  Key Influencers (Trí tuệ nhân tạo của PBI): Tìm xem yếu tố nào tác động mạnh nhất khiến `Turnover_Flag` tăng lên (Ví dụ: Do lương thấp, hay do WLB tệ?).

    *  100% Stacked Column Chart: Trục X là `root_cause_leaving`, chia màu thể hiện mức độ `Performance`. (Lý do: Để Ban giám đốc nhìn thấy ngay nhóm "Người tài" đang tập trung nghỉ việc vì nguyên nhân nào nhất).
"""

# ==============================================================================
# INSIGHT 5: PHÂN RÃ TỶ LỆ NGHỈ VIỆC & NGUYÊN NHÂN GỐC RỄ
# ==============================================================================
import matplotlib.pyplot as plt
import seaborn as sns

print("--- VẼ BIỂU ĐỒ INSIGHT 5: TURNOVER ROOT CAUSE ---")

# DATA PREP: Lọc ra nhóm Tự nguyện nghỉ việc
df_voluntary = df_HR_analyst[df_HR_analyst['turnover_type'] == 'Voluntary']

fig, axes = plt.subplots(1, 2, figsize=(18, 6))

# 1. BIỂU ĐỒ TRÁI: Chảy máu chất xám (Regrettable Turnover)
# Lý do chọn biểu đồ: Countplot kết hợp hue phân lớp Performance.
# Mục tiêu HR: Những người tự nguyện dứt áo ra đi là kẻ kém cỏi hay là nhân tài (High Performer)?
sns.countplot(data=df_voluntary, y='root_cause_leaving', hue='Performance_Group',
              hue_order=['Low', 'Meet', 'High'], palette='rocket', ax=axes[0])
axes[0].set_title('Phân rã Nguyên nhân Nghỉ việc theo Hiệu suất (Chảy máu Chất xám)', fontweight='bold')
axes[0].set_xlabel('Số lượng nhân viên tự nguyện nghỉ')
axes[0].set_ylabel('Nguyên nhân cốt lõi (Root Cause)')
axes[0].legend(title='Hiệu suất')

# 2. BIỂU ĐỒ PHẢI: Bóc trần lời nói dối "Lý do cá nhân" (Polite Quitting)
# Data transformation: Phân loại 3 nhóm:
# (1) Đang làm, (2) Nghỉ do lương/sự nghiệp, (3) Nghỉ viện cớ "Lý do cá nhân"
def categorize_status(row):
    if row['Still Employed'] == True:
        return 'Đang Làm Việc (Active)'
    elif row['root_cause_leaving'] == 'Personal - Life Events':
        return 'Nghỉ - Lý do Cá nhân'
    else:
        return 'Nghỉ - Lý do Khác'

df_HR_analyst['Retention_Status'] = df_HR_analyst.apply(categorize_status, axis=1)

# So sánh Compa-Ratio (Mức độ công bằng lương) của 3 nhóm này
sns.boxplot(data=df_HR_analyst, x='Compa_Ratio', y='Retention_Status', palette='viridis', ax=axes[1])
axes[1].axvline(1.0, color='red', linestyle='--') # Trục chuẩn 1.0
axes[1].set_title('So sánh Độ công bằng Lương (Compa-Ratio) giữa Nhóm Nghỉ & Nhóm Ở lại', fontweight='bold')
axes[1].set_xlabel('Chỉ số Compa-Ratio (Dưới 1 là trả lương thấp)')
axes[1].set_ylabel('Trạng thái')

plt.tight_layout()
plt.show()